### ISSUE TITLE
Personal Notifications Tab not opening

### ISSUE THREAD

**Issue by joneshjain** [Pankajtanwarbanna/PlacementMNIT#3]
User is unable to read Notifications.
Again and again its just showing same message. It's neither opening or getting marked as read.

**Comment by Pankajtanwarbanna** [comment]
Hi,

Notification feature is under Beta testing.

**Comment by Pankajtanwarbanna** [comment]
Hi there,

Notification feature is live. :tada: 

Closing the issue!
