### ISSUE TITLE
IIIT Kota Amazon 50k LPA

### ISSUE THREAD

**Issue by Gaurav9784** [Pankajtanwarbanna/PlacementMNIT#4]
In IIIT Kota section it showing 50K LPA of students which are placed in amazon.
![image](https://user-images.githubusercontent.com/44618810/87711990-a8a39900-c7c5-11ea-8c39-e400489ccf1b.png)

**Comment by Pankajtanwarbanna** [comment]
Hi @Gaurav9784 ,

Thanks for pointing that out. It will be fixed in next update.

Best
Pankaj
