### ISSUE TITLE
About Flags

### ISSUE THREAD

**Issue by 2016uar1152** [Pankajtanwarbanna/PlacementMNIT#5]
In Context of profile.userProfile.red_flags

A lot of students have confusion regarding what is Red flag and why it is imposed upon students.
It would be better if the concept of why and how red flag is applied to you is written in 1 or 2 lines just below those flags.

Yes, it is there that three red flag leads to suspension.
But, having why answered there in short, would be really helpful.
Here,
![Annotation 2020-08-23 225557](https://user-images.githubusercontent.com/35151342/90984694-36785e00-e594-11ea-8f8f-5473dd1a841a.jpg)

**Comment by Pankajtanwarbanna** [comment]
Thanks Pallav @2016uar1152 for pointing it out. It has been into consideration since long. We are planning to add a detailed information about Placement Red Flag policy in next update.

Cheers!

**Comment by Pankajtanwarbanna** [comment]
Hi Pallav, 

Red flag policy information has been updated. Please head over to profile page.

Closing the issue!
