### ISSUE TITLE
Typos Mistake

### ISSUE THREAD

**Issue by 2016uar1152** [Pankajtanwarbanna/PlacementMNIT#8]
In profile user section,
New Red Flag Policy is just added.
It's written Ref flag policy instead of Red Flag Policy.
Here,
![Annotation 2020-09-30 001017](https://user-images.githubusercontent.com/35151342/94601619-5b59a280-02b1-11eb-9940-acf4b2c46d72.jpg)

**Comment by Pankajtanwarbanna** [comment]
Thanks @2016uar1152 . It has been Fixed.
